"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0(t#*&8x&_6-s+$y35uw2yp&m!ado0h&l453(mgp13wkv-27&#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',        # Localhost
    '10.10.3.152',  
     '192.168.1.65' 
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'accounts',
    'vendor',
    'menu',
    'marketplace',
    'django.contrib.gis',
    'customer',
    'order',
    'rest_framework',
    'csp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'order.request_object.RequestObjectMiddleware',#custommiddleware created to access the request object 
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vendor.context_processor.get_vendor',
                'vendor.context_processor.get_google_api',
                'marketplace.context_processor.get_cart_counter',
                'marketplace.context_processor.get_cart_amount',
                'customer.context_processors.get_user_profile',
                'customer.context_processors.get_paypal_client_id',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'
AUTH_USER_MODEL='accounts.User'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'foodonline_db2',
        'USER': 'postgres',
        'PASSWORD': 'Manish@123',
        'HOST': 'localhost',  # Use '127.0.0.1' or the database server's IP
        'PORT': '5432'
       
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT=BASE_DIR/'static'

MEDIA_ROOT=BASE_DIR/'media'
MEDIA_URL='/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_HOST_USER='mahasethmanish63@gmail.com'
EMAIL_HOST_PASSWORD='ptbsykbpcwwrcrnb'
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL='FOODONLINE MARKETPLACE <mahasethmanish63@gmail.com>'
GOOGLE_API_KEY='AIzaSyC8vutbUSfEOTULChADRE3r9UTpqWQVMXY'

os.environ['PATH'] += ';C:\\Users\\Manish Mahaseth\\Desktop\\multivendor4\\venv\\Lib\\site-packages\\osgeo'

# Set the PROJ_LIB path for coordinate transformation
os.environ['PROJ_LIB'] = 'C:\\Users\\Manish Mahaseth\\Desktop\\multivendor4\\venv\\Lib\\site-packages\\osgeo\\data\\proj'

# Set GDAL_LIBRARY_PATH for GDAL to locate the library
GDAL_LIBRARY_PATH = 'C:\\Users\\Manish Mahaseth\\Desktop\\multivendor4\\venv\\Lib\\site-packages\\osgeo\\gdal.dll'


PAYPAL_CLIENT_ID='AZX9UrVFCr_euz3bwcQ-Un32Ok5_r_7ax3sMyw4dnKlcfmvJ8zKOoYp93AGDn0HiGvefec8Ems1MljIC'


SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = None  # Avoid stricter rules

# settings.py

# Celery configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use Redis as the broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Use Redis for storing task results
