# Generated by Django 5.1.1 on 2024-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_category_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
