# Generated by Django 5.1.3 on 2024-11-26 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('COMPLETED', 'Completed'), ('Cancelled', 'Cancelled')], default='NEW', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_foods', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('RazorPay', 'RayzorPay'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], max_length=100),
        ),
    ]
